site_name: Robot Developer Tools for Web
repo_url: https://github.com/ranch-hand-robotics/babylon_ros
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - Installation: installation.md
  - URDF Viewer: urdf.md
  - API Reference:
    - Overview: api-overview.md
    - Core Classes:
      - RobotScene: api/robot-scene.md
      - Robot: api/robot.md
      - Joint: api/joint.md
      - Link: api/link.md
      - Visual: api/visual.md
      - Material: api/material.md
    - Geometry System:
      - Geometry Types: api/geometry.md
    - Interactive Tools:
      - Gizmos: api/gizmos.md
    - Utilities:
      - Helper Functions: api/utilities.md

theme: 
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true

markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
extra:
  copy_files:
    - urdf-viewer.html
    - ros.js

use_directory_urls: false
strict: true